using ChaosWarlords.Source.Utilities;

namespace ChaosWarlords.Source.Entities.Cards
{
    /// <summary>
    /// Represents a card in the game, including its stats, cost, and effects.
    /// Cards can flyweight-like definitions or instantiated objects in a player's deck.
    /// </summary>
    public class Card
    {
        // --- Core Data Only ---

        /// <summary>
        /// Unique identifier for this specific instance of the card.
        /// Essential for distinguishing between identical cards (e.g. two "Drow Soldier" cards).
        /// </summary>
        public Guid RuntimeId { get; private set; } = Guid.NewGuid();

        /// <summary>
        /// Unique identifier for the card definition (e.g. "c_obsidian_golem").
        /// </summary>
        public string Id { get; private set; }

        /// <summary>
        /// The localized name of the card.
        /// </summary>
        public string Name { get; private set; }

        /// <summary>
        /// The influence cost required to purchase this card from the market.
        /// </summary>
        public int Cost { get; private set; }

        /// <summary>
        /// The elemental or factional aspect of the card (e.g. Shadow, Undead).
        /// </summary>
        public CardAspect Aspect { get; private set; }

        /// <summary>
        /// Victory Points worth when in the deck at end of game.
        /// </summary>
        public int DeckVP { get; private set; }

        /// <summary>
        /// Victory Points worth when promoted to the Inner Circle.
        /// </summary>
        public int InnerCircleVP { get; private set; }

        /// <summary>
        /// Influence generated when this card is played.
        /// </summary>
        public int InfluenceValue { get; private set; }

        /// <summary>
        /// List of special effects triggered when the card is played.
        /// </summary>
        public List<CardEffect> Effects { get; private set; } = [];

        /// <summary>
        /// User-visible description of what the card does.
        /// </summary>
        public string Description { get; set; } = "";

        /// <summary>
        /// Current location of this card instance (Deck, Hand, Discard, etc.).
        /// </summary>
        public CardLocation Location { get; set; }

        // Constants moved to GameConstants.CardRendering for centralization
        public static int Width => GameConstants.CardRendering.CardWidth;
        public static int Height => GameConstants.CardRendering.CardHeight;

        public Card(string id, string name, int cost, CardAspect aspect, int deckVp, int innerCircleVp, int influence)
        {
            Id = id;
            Name = name;
            Cost = cost;
            Aspect = aspect;
            DeckVP = deckVp;
            InnerCircleVP = innerCircleVp;
            InfluenceValue = influence;
        }

        public void AddEffect(CardEffect effect)
        {
            Effects.Add(effect);
        }

        public Card Clone()
        {
            var newCard = new Card(Id, Name, Cost, Aspect, DeckVP, InnerCircleVP, InfluenceValue)
            {
                Description = Description,
                Location = Location
                // RuntimeId is automatically generated by the property initializer
            };

            foreach (var effect in Effects)
            {
                newCard.Effects.Add(CloneEffect(effect));
            }

            return newCard;
        }

        // Fully recursive - both OnSuccess ("and then") and Alternative ("instead, if
        // declined/impossible") chains can nest arbitrarily deep (e.g. Cloaker:
        // PlaceSpy.Alternative = ReturnOwnSpy.OnSuccess = Assassinate).
        private static CardEffect CloneEffect(CardEffect effect)
        {
            var newEffect = new CardEffect(effect.Type, effect.Amount, effect.TargetResource)
            {
                RequiresFocus = effect.RequiresFocus,
                IsOptional = effect.IsOptional,
                TargetLocation = effect.TargetLocation,
                ReplaceWithSource = effect.ReplaceWithSource,
                Condition = effect.Condition // Reference copy for condition (usually shared/immutable)
            };

            if (effect.OnSuccess != null)
            {
                newEffect.OnSuccess = CloneEffect(effect.OnSuccess);
            }

            if (effect.Alternative != null)
            {
                newEffect.Alternative = CloneEffect(effect.Alternative);
            }

            return newEffect;
        }
    }
}

